// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoNjrVbO7XuxD1qLd0pum1mjJ53vOBiDU',
    appId: '1:368343776480:web:d8399177e69632b7992485',
    messagingSenderId: '368343776480',
    projectId: 'kondate-ai-prod',
    authDomain: 'kondate-ai-prod.firebaseapp.com',
    storageBucket: 'kondate-ai-prod.firebasestorage.app',
    measurementId: 'G-FJSZ8XS3VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcZe5gQ5S8xYQPyVPrTK1yam-oNU5bVjc',
    appId: '1:368343776480:android:06db315d2e9f117f992485',
    messagingSenderId: '368343776480',
    projectId: 'kondate-ai-prod',
    storageBucket: 'kondate-ai-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoJyv2Mm2pHAmHTR6xHnFCl3I7NXDqLCA',
    appId: '1:368343776480:ios:76e8e82f30820b2b992485',
    messagingSenderId: '368343776480',
    projectId: 'kondate-ai-prod',
    storageBucket: 'kondate-ai-prod.firebasestorage.app',
    iosBundleId: 'com.example.kondateAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoJyv2Mm2pHAmHTR6xHnFCl3I7NXDqLCA',
    appId: '1:368343776480:ios:76e8e82f30820b2b992485',
    messagingSenderId: '368343776480',
    projectId: 'kondate-ai-prod',
    storageBucket: 'kondate-ai-prod.firebasestorage.app',
    iosBundleId: 'com.example.kondateAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoNjrVbO7XuxD1qLd0pum1mjJ53vOBiDU',
    appId: '1:368343776480:web:d8399177e69632b7992485',
    messagingSenderId: '368343776480',
    projectId: 'kondate-ai-prod',
    authDomain: 'kondate-ai-prod.firebaseapp.com',
    storageBucket: 'kondate-ai-prod.firebasestorage.app',
    measurementId: 'G-FJSZ8XS3VQ',
  );
}
